sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: FsUVlTQSWEEZ+N445u20dXM4vFo/CABtn+G/ouSiLi9Zh0jEvduFF7ppeYycjHF3h9f4UsUgvBkRrfL87Jh0sGtCidwRo0iypwilKHxSKqwYO3pVCY/PQD1iPNWR8pcaRLmw7frnRLYCQ7wGoYgwSJ6Ic8rcmfCbD3CE72gda/E2YLhD9ZH2SH9QVBeQTfjEzz3Fgj5BiD31s5Ho28jasVeSZ+1It34Kgqc+gWnkuCXoVByAsPJ/UigbWZBH8MicLyD4STniKYPg16jjEt+ZtF+ERnXeEDuBDKThlf0XwzmCEcsX0M08w566xRvOFauedB8aV0yshYJ0p4YgG5xtGf9C6RvVJ1HKnfWzllNBe5lqhsS06+hVI2CeOHYjXF5MZ4e8x0p50gwVfCmMm8Dk1bgYG//uFucBac+zi7q+6n+opOEsnH/EBci6IPpWR2Kg/DX6AokiB9HKfH3MJvFwX5mimLCGQ8BLYiqtI869muBlISiEhMVEkBQsIvvOducvoVeknyFzkpIo6pjWZDfPvGP2REJ0R6r7sCRk++h7jDIgqaeS9cOxqgqrjcLLD05vFaA0Jmmvv9xg10NbMZUZl7dgcSaGW9i/1JYZu2QM6X18xGHOQsko6F485OvAWR0iExnpGTKqnclesb08YVPF/NWxJsj8MZYJu23/rCiAW1M=
  app: mitestheroku
  on:
    repo: mikrivorot/redis-travis-heroku
  skip_cleanup: 'true'
env:
  global:
    secure: YQaKhWLzjwit1uaLrHd3B/mdQ5glpEwKLBoiDCrjZYR865BQselMRYycpT8qfgKyhf0hytSPn+uAuPwVZqhHhbbzeyz9hODa082Z7bXNdhPif6MEv9sF8lZF4wr0ub/BlMORnkVeZKeoapyu8IwaU91Yqp+ROEhTRNkcYKOGqpJuzLiQuG1f+Py/eh1IN73wg5cnn4rWMF9FOanVuu/FdtqDxNn+7YkLV75lYIAvjEiS8MIvHSucexs9NDfVdsT2lDzug8+jgDZknp/K6tovhRpxGgaSKiApUWoVzHgON5BprPheValqUwMnZ72D/t6an1mmycqVFIQ5+W9uT+m3JCcH9+F9MVa8OwKuvzgV7ZzwuX3yEg7zmspOusJ+vbOKPtnfeaSf5SRYzHAhLCcMSI6WCw0ZMxk3k1LJ8+wvChtMoTqs0JGpocFP4Rb7+J7bWJtuxOvWNGpkaD194tUshKqkNaObu2+SsLR5h1b9B7rlZtnioUEvi+m34a/mbIYrO4YFSp2r6abUMJCHtZFLeq8VXY6SYE2S1dCIQHx87vMoe7MEAQMBQgmhTka2plzUulwSmBw/c/DDLfmFzylEwJWvRqCM7JTlAY7nxej5ZZ7kUm2gQb8FcKn3LlCstz0QYw8AV0OZ6T/Uc3zar82t5Dv/HuzsBN5laokgDkTvEak=
