sudo: false

language: node_js
node_js:
  - 12

branches:
  only:
    - master

deploy:
  provider: heroku
  app: 
    master: mitestheroku
    # production: devmitestheroku
  api_key:
    secure: "afffbfc7-23a1-4cb4-9cea-531be883b0b0"
    